#Pandas

In [1]:
import pandas as pd

##Create Pandas series

In [2]:
s = pd.Series([10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

##Create Pandas series with index

In [3]:
s_ind = pd.Series([100,200,300,400] , index =  ["a" , "b" , "c" , "d"])
s_ind

a    100
b    200
c    300
d    400
dtype: int64

##Pandas series accessing

In [4]:
s[0]

np.int64(10)

In [5]:
s[1]

np.int64(20)

In [6]:
s_ind['a']

np.int64(100)

In [7]:
s_ind['b']

np.int64(200)

#1.Inspection Functions

In [8]:
data = {
    "ID" : [101,102,103,104,105,106],
    "Name" : ["John" , "Alice" , "Rose" , "Bob" , "Jack","Eva"],
    "Salary" : [10000,20000,30000,40000,50000,60000],
    "Department" : ["HR" , "IT" , "HR" , "IT" , "IT" , "Finance"]
}

In [9]:
df = pd.DataFrame(data)

In [10]:
df

    ID   Name  Salary Department
0  101   John   10000         HR
1  102  Alice   20000         IT
2  103   Rose   30000         HR
3  104    Bob   40000         IT
4  105   Jack   50000         IT
5  106    Eva   60000    Finance

##head()
return first n rows

5 by deafult

In [11]:
df.head()

    ID   Name  Salary Department
0  101   John   10000         HR
1  102  Alice   20000         IT
2  103   Rose   30000         HR
3  104    Bob   40000         IT
4  105   Jack   50000         IT

In [12]:
df.head(3)

    ID   Name  Salary Department
0  101   John   10000         HR
1  102  Alice   20000         IT
2  103   Rose   30000         HR

##tail() ->
return last row

In [13]:
df.tail()

    ID   Name  Salary Department
1  102  Alice   20000         IT
2  103   Rose   30000         HR
3  104    Bob   40000         IT
4  105   Jack   50000         IT
5  106    Eva   60000    Finance

In [14]:
df.tail(3)

    ID  Name  Salary Department
3  104   Bob   40000         IT
4  105  Jack   50000         IT
5  106   Eva   60000    Finance

##info()

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          6 non-null      int64
 1   Name        6 non-null      object
 2   Salary      6 non-null      int64
 3   Department  6 non-null      object
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

###True → Show information for every column.

In [16]:
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          6 non-null      int64
 1   Name        6 non-null      object
 2   Salary      6 non-null      int64
 3   Department  6 non-null      object
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

###False → Show only a summary (especially useful when there are many columns).

In [17]:
df.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Columns: 4 entries, ID to Department
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

###memory_usage="deep"  -> gives actual memory usage

In [18]:
df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          6 non-null      int64
 1   Name        6 non-null      object
 2   Salary      6 non-null      int64
 3   Department  6 non-null      object
dtypes: int64(2), object(2)
memory usage: 856.0 bytes

##Shape

In [19]:
df.shape

(6, 4)

##describe()

In [20]:
df.describe()

               ID        Salary
count    6.000000      6.000000
mean   103.500000  35000.000000
std      1.870829  18708.286934
min    101.000000  10000.000000
25%    102.250000  22500.000000
50%    103.500000  35000.000000
75%    104.750000  47500.000000
max    106.000000  60000.000000

##columns

In [21]:
df.columns

Index(['ID', 'Name', 'Salary', 'Department'], dtype='object')

In [22]:
list(df.columns)

['ID', 'Name', 'Salary', 'Department']

##Index

In [23]:
df.index

RangeIndex(start=0, stop=6, step=1)

##dtypes - > datatypes

In [24]:
df.dtypes

ID             int64
Name          object
Salary         int64
Department    object
dtype: object

##size
total element (rows * columns)

In [25]:
df.size

24

##memory_usage()
show memory consume by every columns

In [26]:
df.memory_usage()

Index         132
ID             48
Name           48
Salary         48
Department     48
dtype: int64

In [27]:
df.memory_usage(deep=True)
#actual memory used

Index         132
ID             48
Name          317
Salary         48
Department    311
dtype: int64

#2.Selecting Data

###A. Select a Single Column

In [28]:
df["Name"]

0     John
1    Alice
2     Rose
3      Bob
4     Jack
5      Eva
Name: Name, dtype: object

In [29]:
df["ID"]

0    101
1    102
2    103
3    104
4    105
5    106
Name: ID, dtype: int64

###B. Select Multiple Columns

In [30]:
df[["ID" , "Name" , "Department"]]

    ID   Name Department
0  101   John         HR
1  102  Alice         IT
2  103   Rose         HR
3  104    Bob         IT
4  105   Jack         IT
5  106    Eva    Finance

###C. Select All Columns

In [31]:
df[:]

    ID   Name  Salary Department
0  101   John   10000         HR
1  102  Alice   20000         IT
2  103   Rose   30000         HR
3  104    Bob   40000         IT
4  105   Jack   50000         IT
5  106    Eva   60000    Finance

###D. Select Column Using Dot Notation

In [32]:
df.Name

0     John
1    Alice
2     Rose
3      Bob
4     Jack
5      Eva
Name: Name, dtype: object

In [33]:
df.ID

0    101
1    102
2    103
3    104
4    105
5    106
Name: ID, dtype: int64

#3.loc[] (Label-Based Selection)

loc selects rows and columns using labels

In [34]:
#select one row
df.loc[2]

ID              103
Name           Rose
Salary        30000
Department       HR
Name: 2, dtype: object

In [35]:
#select multiple row
df.loc[[1,2]]

    ID   Name  Salary Department
1  102  Alice   20000         IT
2  103   Rose   30000         HR

In [36]:
#Select a Specific Value
df.loc[1 , "Name"]

'Alice'

In [37]:
#Select Specific Rows and Columns
df.loc[[0,2] , ["Name" ,  "Department"]]

   Name Department
0  John         HR
2  Rose         HR

#4.iloc[] (Position-Based Selection)

iloc selects rows and columns using integer positions.

In [38]:
df.iloc[2,1]
#row 2and column 1

'Rose'

In [39]:
df.iloc[[0,2] , [1,3]]

   Name Department
0  John         HR
2  Rose         HR

#5.Filtering

Filtering means selecting rows based on conditions.

In [40]:
df[df["Salary"] > 20000]

    ID  Name  Salary Department
2  103  Rose   30000         HR
3  104   Bob   40000         IT
4  105  Jack   50000         IT
5  106   Eva   60000    Finance

In [41]:
df[df['Department'] == "IT"]

    ID   Name  Salary Department
1  102  Alice   20000         IT
3  104    Bob   40000         IT
4  105   Jack   50000         IT

In [42]:
#and
df[(df['Salary'] < 30000) & (df['Department'] == "IT")]

    ID   Name  Salary Department
1  102  Alice   20000         IT

In [43]:
# or
df[(df['ID'] > 104) | (df['Department'] == "HR")]

    ID  Name  Salary Department
0  101  John   10000         HR
2  103  Rose   30000         HR
4  105  Jack   50000         IT
5  106   Eva   60000    Finance

In [44]:
#not equal
df[df["Department"] != "HR"]

    ID   Name  Salary Department
1  102  Alice   20000         IT
3  104    Bob   40000         IT
4  105   Jack   50000         IT
5  106    Eva   60000    Finance

In [45]:
#isin
df[df['Department'].isin(["IT" , "HR"])]

    ID   Name  Salary Department
0  101   John   10000         HR
1  102  Alice   20000         IT
2  103   Rose   30000         HR
3  104    Bob   40000         IT
4  105   Jack   50000         IT

In [46]:
#between()
df[df['Salary'].between(20000,50000)]

    ID   Name  Salary Department
1  102  Alice   20000         IT
2  103   Rose   30000         HR
3  104    Bob   40000         IT
4  105   Jack   50000         IT

#6.Sorting

In [47]:
df

    ID   Name  Salary Department
0  101   John   10000         HR
1  102  Alice   20000         IT
2  103   Rose   30000         HR
3  104    Bob   40000         IT
4  105   Jack   50000         IT
5  106    Eva   60000    Finance

In [48]:
df.sort_values("Department")

    ID   Name  Salary Department
5  106    Eva   60000    Finance
0  101   John   10000         HR
2  103   Rose   30000         HR
1  102  Alice   20000         IT
3  104    Bob   40000         IT
4  105   Jack   50000         IT

In [49]:
#descending
df.sort_values("Salary" , ascending=False)

    ID   Name  Salary Department
5  106    Eva   60000    Finance
4  105   Jack   50000         IT
3  104    Bob   40000         IT
2  103   Rose   30000         HR
1  102  Alice   20000         IT
0  101   John   10000         HR

#7.Rename()
to change name of column

In [50]:
#before change
df

    ID   Name  Salary Department
0  101   John   10000         HR
1  102  Alice   20000         IT
2  103   Rose   30000         HR
3  104    Bob   40000         IT
4  105   Jack   50000         IT
5  106    Eva   60000    Finance

In [51]:
df.rename(columns={"ID":"EmployeeID"})

   EmployeeID   Name  Salary Department
0         101   John   10000         HR
1         102  Alice   20000         IT
2         103   Rose   30000         HR
3         104    Bob   40000         IT
4         105   Jack   50000         IT
5         106    Eva   60000    Finance

only rename will modify name but not orignal dataframe

In [52]:
df

    ID   Name  Salary Department
0  101   John   10000         HR
1  102  Alice   20000         IT
2  103   Rose   30000         HR
3  104    Bob   40000         IT
4  105   Jack   50000         IT
5  106    Eva   60000    Finance

By default, rename() returns a new DataFrame. Use inplace=True to modify the original DataFrame.

In [53]:
df.rename(columns={"ID":"EmpID"} , inplace=True)

In [54]:
df

   EmpID   Name  Salary Department
0    101   John   10000         HR
1    102  Alice   20000         IT
2    103   Rose   30000         HR
3    104    Bob   40000         IT
4    105   Jack   50000         IT
5    106    Eva   60000    Finance

#8.drop() method is used to remove rows or columns

In [55]:
#remove rows
df.drop(3)

   EmpID   Name  Salary Department
0    101   John   10000         HR
1    102  Alice   20000         IT
2    103   Rose   30000         HR
4    105   Jack   50000         IT
5    106    Eva   60000    Finance

In [56]:
df

   EmpID   Name  Salary Department
0    101   John   10000         HR
1    102  Alice   20000         IT
2    103   Rose   30000         HR
3    104    Bob   40000         IT
4    105   Jack   50000         IT
5    106    Eva   60000    Finance

In [57]:
#remove multiple rows
df.drop([1,3])

   EmpID  Name  Salary Department
0    101  John   10000         HR
2    103  Rose   30000         HR
4    105  Jack   50000         IT
5    106   Eva   60000    Finance

In [58]:
#remove colunms
df.drop("Name",axis=1)

   EmpID  Salary Department
0    101   10000         HR
1    102   20000         IT
2    103   30000         HR
3    104   40000         IT
4    105   50000         IT
5    106   60000    Finance

In [59]:
df.drop(["Name","Salary"] , axis=1)

   EmpID Department
0    101         HR
1    102         IT
2    103         HR
3    104         IT
4    105         IT
5    106    Finance

In [60]:
df
#no change

   EmpID   Name  Salary Department
0    101   John   10000         HR
1    102  Alice   20000         IT
2    103   Rose   30000         HR
3    104    Bob   40000         IT
4    105   Jack   50000         IT
5    106    Eva   60000    Finance

drop() does not change the original DataFrame unless inplace=True is used.

In [61]:
df.drop(5,inplace=True)

In [62]:
df

   EmpID   Name  Salary Department
0    101   John   10000         HR
1    102  Alice   20000         IT
2    103   Rose   30000         HR
3    104    Bob   40000         IT
4    105   Jack   50000         IT

In [63]:
df.drop("EmpID",axis=1 ,  inplace=True)

#9. Add (Insert) a Column

A new column can be added by assigning a value to a new column name.

In [64]:
df["EmpId"]=100

In [65]:
df

    Name  Salary Department  EmpId
0   John   10000         HR    100
1  Alice   20000         IT    100
2   Rose   30000         HR    100
3    Bob   40000         IT    100
4   Jack   50000         IT    100

In [66]:
df["EmpId"]=[101,102,103,104,105]

In [67]:
df

    Name  Salary Department  EmpId
0   John   10000         HR    101
1  Alice   20000         IT    102
2   Rose   30000         HR    103
3    Bob   40000         IT    104
4   Jack   50000         IT    105

In [68]:
df.drop("EmpId" , axis=1,inplace=True)

##insert()

In [69]:
df.insert(0,"EmpId",[100,101,102,103,104])

In [70]:
df

   EmpId   Name  Salary Department
0    100   John   10000         HR
1    101  Alice   20000         IT
2    102   Rose   30000         HR
3    103    Bob   40000         IT
4    104   Jack   50000         IT

In [71]:
df.insert(4,"Gender",["M","M","F","M","F"])

In [72]:
df

   EmpId   Name  Salary Department Gender
0    100   John   10000         HR      M
1    101  Alice   20000         IT      M
2    102   Rose   30000         HR      F
3    103    Bob   40000         IT      M
4    104   Jack   50000         IT      F

#10.ways to remove columns


1.   del :- Removes the column permanently
2.   pop():- Removes the column and returns it as a Series
3.   drop()

In [73]:
del df["Gender"]

In [74]:
df

   EmpId   Name  Salary Department
0    100   John   10000         HR
1    101  Alice   20000         IT
2    102   Rose   30000         HR
3    103    Bob   40000         IT
4    104   Jack   50000         IT

In [75]:
df.pop("Salary")

0    10000
1    20000
2    30000
3    40000
4    50000
Name: Salary, dtype: int64

In [76]:
df

   EmpId   Name Department
0    100   John         HR
1    101  Alice         IT
2    102   Rose         HR
3    103    Bob         IT
4    104   Jack         IT

#New Dataframe

In [77]:
import pandas as pd
import numpy as np

In [78]:
data = {
    "ID":[10,20,30,40,50],
    "Name":["John", "Alice", "Bob", "John", np.nan],
    "Age":[25,30,26,np.nan,70],
    "Gender":["M","F",np.nan,"M","F"]
}

In [79]:
df = pd.DataFrame(data)

In [80]:
df

   ID   Name   Age Gender
0  10   John  25.0      M
1  20  Alice  30.0      F
2  30    Bob  26.0    NaN
3  40   John   NaN      M
4  50    NaN  70.0      F

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      5 non-null      int64
 1   Name    4 non-null      object
 2   Age     4 non-null      float64
 3   Gender  4 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

#11. Missing Values

In [82]:
#check missing value
df.isnull()

      ID   Name    Age  Gender
0  False  False  False   False
1  False  False  False   False
2  False  False  False    True
3  False  False   True   False
4  False   True  False   False

In [83]:
#count of missing value
df.isnull().sum()

ID        0
Name      1
Age       1
Gender    1
dtype: int64

In [84]:
#check non misisng value
df.notnull()

     ID   Name    Age  Gender
0  True   True   True    True
1  True   True   True    True
2  True   True   True   False
3  True   True  False    True
4  True  False   True    True

In [85]:
#count non missing value
df.notnull().sum()

ID        5
Name      4
Age       4
Gender    4
dtype: int64

In [86]:
#same as isnull()
df.isna()

      ID   Name    Age  Gender
0  False  False  False   False
1  False  False  False   False
2  False  False  False    True
3  False  False   True   False
4  False   True  False   False

In [87]:
df.notna()

     ID   Name    Age  Gender
0  True   True   True    True
1  True   True   True    True
2  True   True   True   False
3  True   True  False    True
4  True  False   True    True

In [88]:
df

   ID   Name   Age Gender
0  10   John  25.0      M
1  20  Alice  30.0      F
2  30    Bob  26.0    NaN
3  40   John   NaN      M
4  50    NaN  70.0      F

#12. fillna()
this method is used to replace missing (NaN) values.

In [89]:
#replace with fixed value
df.fillna(0)

   ID   Name   Age Gender
0  10   John  25.0      M
1  20  Alice  30.0      F
2  30    Bob  26.0      0
3  40   John   0.0      M
4  50      0  70.0      F

In [90]:
#Fill with mean
df["Age"].fillna(df["Age"].mean())

0    25.00
1    30.00
2    26.00
3    37.75
4    70.00
Name: Age, dtype: float64

In [91]:
#Forward fill(ffill)
df.fillna(method="ffill")

/tmp/ipykernel_9413/2752464886.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

   ID   Name   Age Gender
0  10   John  25.0      M
1  20  Alice  30.0      F
2  30    Bob  26.0      F
3  40   John  26.0      M
4  50   John  70.0      F

In [92]:
#Backward fill(bfill)
df.fillna(method="bfill")

/tmp/ipykernel_9413/2854960756.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill")

   ID   Name   Age Gender
0  10   John  25.0      M
1  20  Alice  30.0      F
2  30    Bob  26.0      M
3  40   John  70.0      M
4  50    NaN  70.0      F

#13.dropna()
The dropna() method removes rows or columns containing missing values.

In [93]:
df

   ID   Name   Age Gender
0  10   John  25.0      M
1  20  Alice  30.0      F
2  30    Bob  26.0    NaN
3  40   John   NaN      M
4  50    NaN  70.0      F

In [94]:
#remove rows by default
df.dropna()

   ID   Name   Age Gender
0  10   John  25.0      M
1  20  Alice  30.0      F

In [95]:
#remove columns
df.dropna(axis=1)

   ID
0  10
1  20
2  30
3  40
4  50

The how parameter tells Pandas when to remove them.

how="any" (default) → Remove if at least one value is NaN.
how="all" → Remove only if every value in the row (or column) is NaN.

#14.Duplicates

In [96]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

Remove Duplicate Rows

df.drop_duplicates()

In [97]:
#Remove Duplicates Based on One Column
df.drop_duplicates(subset="Gender")

   ID   Name   Age Gender
0  10   John  25.0      M
1  20  Alice  30.0      F
2  30    Bob  26.0    NaN

In [98]:
df.drop_duplicates(subset="Name")

   ID   Name   Age Gender
0  10   John  25.0      M
1  20  Alice  30.0      F
2  30    Bob  26.0    NaN
4  50    NaN  70.0      F

#15.String Function (.str)

In [99]:
df

   ID   Name   Age Gender
0  10   John  25.0      M
1  20  Alice  30.0      F
2  30    Bob  26.0    NaN
3  40   John   NaN      M
4  50    NaN  70.0      F

##1.Convert to uppercase

In [100]:
df["Name"].str.upper()

0     JOHN
1    ALICE
2      BOB
3     JOHN
4      NaN
Name: Name, dtype: object

##2.Convert to lowercase

In [101]:
df["Name"].str.lower()

0     john
1    alice
2      bob
3     john
4      NaN
Name: Name, dtype: object

##3. get string length

In [102]:
df["Name"].str.len()

0    4.0
1    5.0
2    3.0
3    4.0
4    NaN
Name: Name, dtype: float64

##4.Check if string contain text

In [103]:
df['Name'].str.contains("Jo")

0     True
1    False
2    False
3     True
4      NaN
Name: Name, dtype: object

##5.Replace Text

In [104]:
df['Name'].str.replace("John","mike")

0     mike
1    Alice
2      Bob
3     mike
4      NaN
Name: Name, dtype: object

##6.split Text

In [105]:
df

   ID   Name   Age Gender
0  10   John  25.0      M
1  20  Alice  30.0      F
2  30    Bob  26.0    NaN
3  40   John   NaN      M
4  50    NaN  70.0      F

In [106]:
df.insert(4,"Email",["john10@gamil","alice20@gamil","bob30@gamil","john40@gamil","NaN50@gamil"])

In [107]:
df

   ID   Name   Age Gender          Email
0  10   John  25.0      M   john10@gamil
1  20  Alice  30.0      F  alice20@gamil
2  30    Bob  26.0    NaN    bob30@gamil
3  40   John   NaN      M   john40@gamil
4  50    NaN  70.0      F    NaN50@gamil

In [108]:
df["Email"].str.split("@")

0     [john10, gamil]
1    [alice20, gamil]
2      [bob30, gamil]
3     [john40, gamil]
4      [NaN50, gamil]
Name: Email, dtype: object

##7.check starting charater

In [109]:
df["Name"].str.startswith("A")

0    False
1     True
2    False
3    False
4      NaN
Name: Name, dtype: object

##8..check Ending charater

In [110]:
df["Name"].str.endswith("n")

0     True
1    False
2    False
3     True
4      NaN
Name: Name, dtype: object

#15.Map()

In [111]:
df["Gender"].map({
    "M": "Male",
    "F": "Female"
})

0      Male
1    Female
2       NaN
3      Male
4    Female
Name: Gender, dtype: object

In [112]:
df

   ID   Name   Age Gender          Email
0  10   John  25.0      M   john10@gamil
1  20  Alice  30.0      F  alice20@gamil
2  30    Bob  26.0    NaN    bob30@gamil
3  40   John   NaN      M   john40@gamil
4  50    NaN  70.0      F    NaN50@gamil

#16.unique()

In [114]:
df.insert(4,"Department", ["HR" , "IT" , "HR" , "IT" , "Finance"])

In [115]:
df

   ID   Name   Age Gender Department          Email
0  10   John  25.0      M         HR   john10@gamil
1  20  Alice  30.0      F         IT  alice20@gamil
2  30    Bob  26.0    NaN         HR    bob30@gamil
3  40   John   NaN      M         IT   john40@gamil
4  50    NaN  70.0      F    Finance    NaN50@gamil

In [117]:
df["Department"].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

#17.nunique

In [118]:
df["Department"].nunique()

3

#18.value_counts()

In [120]:
df["Department"].value_counts()

Department
HR         2
IT         2
Finance    1
Name: count, dtype: int64

#19.astype

In [126]:
df.insert(5,"Salary",[1000,2000,3000,4000,5000])

In [127]:
df

   ID   Name   Age Gender Department  Salary          Email
0  10   John  25.0      M         HR    1000   john10@gamil
1  20  Alice  30.0      F         IT    2000  alice20@gamil
2  30    Bob  26.0    NaN         HR    3000    bob30@gamil
3  40   John   NaN      M         IT    4000   john40@gamil
4  50    NaN  70.0      F    Finance    5000    NaN50@gamil

In [128]:
df["Salary"].astype("float")

0    1000.0
1    2000.0
2    3000.0
3    4000.0
4    5000.0
Name: Salary, dtype: float64

In [129]:
df

   ID   Name   Age Gender Department  Salary          Email
0  10   John  25.0      M         HR    1000   john10@gamil
1  20  Alice  30.0      F         IT    2000  alice20@gamil
2  30    Bob  26.0    NaN         HR    3000    bob30@gamil
3  40   John   NaN      M         IT    4000   john40@gamil
4  50    NaN  70.0      F    Finance    5000    NaN50@gamil

#20.set_index()

In [133]:
df.set_index("ID")

     Name   Age Gender Department  Salary          Email
ID
10   John  25.0      M         HR    1000   john10@gamil
20  Alice  30.0      F         IT    2000  alice20@gamil
30    Bob  26.0    NaN         HR    3000    bob30@gamil
40   John   NaN      M         IT    4000   john40@gamil
50    NaN  70.0      F    Finance    5000    NaN50@gamil

#21.merge()

In [136]:
location = pd.DataFrame({
    "ID":[10,20,30,40,50],
    "City":["Pune","Mumbai","Delhi","Hyderabad","Chennai"]
})

In [137]:
location

   ID       City
0  10       Pune
1  20     Mumbai
2  30      Delhi
3  40  Hyderabad
4  50    Chennai

In [138]:
pd.merge(df,location,on="ID")

   ID   Name   Age Gender Department  Salary          Email       City
0  10   John  25.0      M         HR    1000   john10@gamil       Pune
1  20  Alice  30.0      F         IT    2000  alice20@gamil     Mumbai
2  30    Bob  26.0    NaN         HR    3000    bob30@gamil      Delhi
3  40   John   NaN      M         IT    4000   john40@gamil  Hyderabad
4  50    NaN  70.0      F    Finance    5000    NaN50@gamil    Chennai

#22.concat():
concat() is used to combine (stack) two or more DataFrames.

There are two ways to concatenate:

Vertically (one below another) → axis=0 (default)

Horizontally (side by side) → axis=1

In [142]:
#vertically
pd.concat([df,location])

   ID   Name   Age Gender Department  Salary          Email       City
0  10   John  25.0      M         HR  1000.0   john10@gamil        NaN
1  20  Alice  30.0      F         IT  2000.0  alice20@gamil        NaN
2  30    Bob  26.0    NaN         HR  3000.0    bob30@gamil        NaN
3  40   John   NaN      M         IT  4000.0   john40@gamil        NaN
4  50    NaN  70.0      F    Finance  5000.0    NaN50@gamil        NaN
0  10    NaN   NaN    NaN        NaN     NaN            NaN       Pune
1  20    NaN   NaN    NaN        NaN     NaN            NaN     Mumbai
2  30    NaN   NaN    NaN        NaN     NaN            NaN      Delhi
3  40    NaN   NaN    NaN        NaN     NaN            NaN  Hyderabad
4  50    NaN   NaN    NaN        NaN     NaN            NaN    Chennai

In [141]:
#horizontally
pd.concat([df,location],axis=1)

   ID   Name   Age Gender Department  Salary          Email  ID       City
0  10   John  25.0      M         HR    1000   john10@gamil  10       Pune
1  20  Alice  30.0      F         IT    2000  alice20@gamil  20     Mumbai
2  30    Bob  26.0    NaN         HR    3000    bob30@gamil  30      Delhi
3  40   John   NaN      M         IT    4000   john40@gamil  40  Hyderabad
4  50    NaN  70.0      F    Finance    5000    NaN50@gamil  50    Chennai

#23.join()

In [148]:
#df.join(location)

#24.pivot_table()

In [153]:

df.pivot_table(
    values="Salary",
    index="Department",
    aggfunc="sum"
)

            Salary
Department
Finance       5000
HR            4000
IT            6000